export const test = [
  {
    id: 50,
    name: '领用管理',
    parentId: 1,
    url: '/receive',
    code: 'box:receiveApply',
    icon: 'receive',
    type: 1,
    level: 1,
    state: 1,
    sort: 0,
    remark: 'Receive',
    version: 0,
    createTime: '2019-10-26 11:15:48',
    updateTime: null,
    component: null,
    maxLevel: 2,
    children: [
      {
        id: 1703,
        name: '领用信息详情',
        parentId: 500,
        url: null,
        code: 'box:receiveApply:view',
        icon: 'el-icon-s-unfold',
        type: 2,
        level: 3,
        state: 1,
        sort: 0,
        remark: '',
        version: 0,
        createTime: '2019-10-26 11:15:48',
        updateTime: null,
        component: null,
        maxLevel: null,
        children: []
      },
      {
        id: 1704,
        name: '领用信息列表',
        parentId: 500,
        url: null,
        code: 'box:receiveApply:list',
        icon: 'el-icon-s-unfold',
        type: 2,
        level: 3,
        state: 1,
        sort: 0,
        remark: '',
        version: 0,
        createTime: '2019-10-26 11:15:48',
        updateTime: null,
        component: null,
        maxLevel: null,
        children: []
      }
    ]
  },
  {
    id: 60,
    name: '格口管理',
    parentId: 1,
    url: '/grid',
    code: 'box:boxInfo',
    icon: 'grid',
    type: 1,
    level: 1,
    state: 1,
    sort: 0,
    remark: 'Grid',
    version: 0,
    createTime: '2019-10-26 11:15:48',
    updateTime: null,
    component: null,
    maxLevel: 3,
    children: [
      {
        id: 510,
        name: '格口管理',
        parentId: 60,
        url: 'info',
        code: 'box:boxInfo:second',
        icon: 'grid',
        type: 1,
        level: 2,
        state: 1,
        sort: 0,
        remark: 'GridInfo',
        version: 0,
        createTime: '2019-10-26 11:18:40',
        updateTime: null,
        component: 'grid/info',
        maxLevel: null,
        children: [
          {
            id: 1801,
            name: '格口信息修改',
            parentId: 510,
            url: null,
            code: 'box:boxInfo:edit',
            icon: 'el-icon-s-unfold',
            type: 2,
            level: 3,
            state: 1,
            sort: 0,
            remark: '',
            version: 0,
            createTime: '2019-10-26 11:15:48',
            updateTime: null,
            component: null,
            maxLevel: null,
            children: []
          },
          {
            id: 1802,
            name: '格口详情',
            parentId: 510,
            url: null,
            code: 'box:boxInfo:view',
            icon: 'el-icon-s-unfold',
            type: 2,
            level: 3,
            state: 1,
            sort: 0,
            remark: '',
            version: 0,
            createTime: '2019-10-26 11:15:48',
            updateTime: null,
            component: null,
            maxLevel: null,
            children: []
          },
          {
            id: 1804,
            name: '格口列表',
            parentId: 510,
            url: null,
            code: 'box:boxInfo:page',
            icon: 'el-icon-s-unfold',
            type: 2,
            level: 3,
            state: 1,
            sort: 0,
            remark: '',
            version: 0,
            createTime: '2019-10-26 11:15:48',
            updateTime: null,
            component: null,
            maxLevel: null,
            children: []
          },
          {
            id: 1805,
            name: '盘点',
            parentId: 510,
            url: null,
            code: 'box:boxInfo:remoteCheck',
            icon: 'el-icon-s-unfold',
            type: 2,
            level: 3,
            state: 1,
            sort: 0,
            remark: '',
            version: 0,
            createTime: '2019-10-26 11:15:48',
            updateTime: null,
            component: null,
            maxLevel: null,
            children: []
          },
          {
            id: 1806,
            name: '开锁',
            parentId: 510,
            url: null,
            code: 'box:boxInfo:remoteUnLock',
            icon: 'el-icon-s-unfold',
            type: 2,
            level: 3,
            state: 1,
            sort: 0,
            remark: '',
            version: 0,
            createTime: '2019-10-26 11:15:48',
            updateTime: null,
            component: null,
            maxLevel: null,
            children: []
          },
          {
            id: 1807,
            name: '盘点全部',
            parentId: 510,
            url: null,
            code: 'box:boxInfo:remoteAllCheck',
            icon: 'el-icon-s-unfold',
            type: 2,
            level: 3,
            state: 1,
            sort: 0,
            remark: '',
            version: 0,
            createTime: '2019-10-26 11:15:48',
            updateTime: null,
            component: null,
            maxLevel: null,
            children: []
          }
        ]
      },
      {
        id: 511,
        name: '格口类型',
        parentId: 60,
        url: 'grid',
        code: 'box:boxType:second',
        icon: 'grid',
        type: 1,
        level: 2,
        state: 1,
        sort: 0,
        remark: 'GridGrid',
        version: 0,
        createTime: '2019-10-26 11:18:40',
        updateTime: null,
        component: 'grid/grid',
        maxLevel: null,
        children: [
          {
            id: 1901,
            name: '格口类型列表',
            parentId: 511,
            url: null,
            code: 'box:boxType:list',
            icon: 'el-icon-s-unfold',
            type: 2,
            level: 3,
            state: 1,
            sort: 0,
            remark: '',
            version: 0,
            createTime: '2019-10-26 11:15:48',
            updateTime: null,
            component: null,
            maxLevel: null,
            children: []
          },
          {
            id: 1902,
            name: '格口类型新增',
            parentId: 511,
            url: null,
            code: 'box:boxType:add',
            icon: 'el-icon-s-unfold',
            type: 2,
            level: 3,
            state: 1,
            sort: 0,
            remark: '',
            version: 0,
            createTime: '2019-10-26 11:15:48',
            updateTime: null,
            component: null,
            maxLevel: null,
            children: []
          },
          {
            id: 1903,
            name: '格口类型修改',
            parentId: 511,
            url: null,
            code: 'box:boxType:edit',
            icon: 'el-icon-s-unfold',
            type: 2,
            level: 3,
            state: 1,
            sort: 0,
            remark: '',
            version: 0,
            createTime: '2019-10-26 11:15:48',
            updateTime: null,
            component: null,
            maxLevel: null,
            children: []
          },
          {
            id: 1904,
            name: '格口类型删除',
            parentId: 511,
            url: null,
            code: 'box:boxType:delete',
            icon: 'el-icon-s-unfold',
            type: 2,
            level: 3,
            state: 1,
            sort: 0,
            remark: '',
            version: 0,
            createTime: '2019-10-26 11:15:48',
            updateTime: null,
            component: null,
            maxLevel: null,
            children: []
          }
        ]
      }
    ]
  },
  {
    id: 70,
    name: '物品管理',
    parentId: 1,
    url: '/goods',
    code: 'box:boxProduct',
    icon: 'goods',
    type: 1,
    level: 1,
    state: 1,
    sort: 0,
    remark: 'Goods',
    version: 0,
    createTime: '2019-10-26 11:15:48',
    updateTime: null,
    component: null,
    maxLevel: 2,
    children: [
      {
        id: 2000,
        name: '物品列表',
        parentId: 520,
        url: null,
        code: 'box:boxProduct:page',
        icon: 'el-icon-s-unfold',
        type: 2,
        level: 3,
        state: 1,
        sort: 0,
        remark: '',
        version: 0,
        createTime: '2019-10-26 11:15:48',
        updateTime: null,
        component: null,
        maxLevel: null,
        children: []
      },
      {
        id: 2001,
        name: '物品新增',
        parentId: 520,
        url: null,
        code: 'box:boxProduct:add',
        icon: 'el-icon-s-unfold',
        type: 2,
        level: 3,
        state: 1,
        sort: 0,
        remark: '',
        version: 0,
        createTime: '2019-10-26 11:15:48',
        updateTime: null,
        component: null,
        maxLevel: null,
        children: []
      },
      {
        id: 2002,
        name: '物品修改',
        parentId: 520,
        url: null,
        code: 'box:boxProduct:edit',
        icon: 'el-icon-s-unfold',
        type: 2,
        level: 3,
        state: 1,
        sort: 0,
        remark: '',
        version: 0,
        createTime: '2019-10-26 11:15:48',
        updateTime: null,
        component: null,
        maxLevel: null,
        children: []
      },
      {
        id: 2003,
        name: '物品详情',
        parentId: 520,
        url: null,
        code: 'box:boxProduct:view',
        icon: 'el-icon-s-unfold',
        type: 2,
        level: 3,
        state: 1,
        sort: 0,
        remark: '',
        version: 0,
        createTime: '2019-10-26 11:15:48',
        updateTime: null,
        component: null,
        maxLevel: null,
        children: []
      },
      {
        id: 2004,
        name: '物品导入',
        parentId: 520,
        url: null,
        code: 'box:boxProduct:importData',
        icon: 'el-icon-s-unfold',
        type: 2,
        level: 3,
        state: 1,
        sort: 0,
        remark: '',
        version: 0,
        createTime: '2019-10-26 11:15:48',
        updateTime: null,
        component: null,
        maxLevel: null,
        children: []
      },
      {
        id: 2005,
        name: '物品导出',
        parentId: 520,
        url: null,
        code: 'box:boxProduct:export',
        icon: 'el-icon-s-unfold',
        type: 2,
        level: 3,
        state: 1,
        sort: 0,
        remark: '',
        version: 0,
        createTime: '2019-10-26 11:15:48',
        updateTime: null,
        component: null,
        maxLevel: null,
        children: []
      },
      {
        id: 2006,
        name: '物品类型新增',
        parentId: 520,
        url: null,
        code: 'box:productType:add',
        icon: 'el-icon-s-unfold',
        type: 2,
        level: 3,
        state: 1,
        sort: 0,
        remark: '',
        version: 0,
        createTime: '2019-10-26 11:15:48',
        updateTime: null,
        component: null,
        maxLevel: null,
        children: []
      },
      {
        id: 2007,
        name: '物品类型修改',
        parentId: 520,
        url: null,
        code: 'box:productType:edit',
        icon: 'el-icon-s-unfold',
        type: 2,
        level: 3,
        state: 1,
        sort: 0,
        remark: '',
        version: 0,
        createTime: '2019-10-26 11:15:48',
        updateTime: null,
        component: null,
        maxLevel: null,
        children: []
      },
      {
        id: 2008,
        name: '物品类型详情',
        parentId: 520,
        url: null,
        code: 'box:productType:view',
        icon: 'el-icon-s-unfold',
        type: 2,
        level: 3,
        state: 1,
        sort: 0,
        remark: '',
        version: 0,
        createTime: '2019-10-26 11:15:48',
        updateTime: null,
        component: null,
        maxLevel: null,
        children: []
      },
      {
        id: 2009,
        name: '物品类型删除',
        parentId: 520,
        url: null,
        code: 'box:productType:delete',
        icon: 'el-icon-s-unfold',
        type: 2,
        level: 3,
        state: 1,
        sort: 0,
        remark: '',
        version: 0,
        createTime: '2019-10-26 11:15:48',
        updateTime: null,
        component: null,
        maxLevel: null,
        children: []
      },
      {
        id: 2010,
        name: '物品类型上移',
        parentId: 520,
        url: null,
        code: 'box:productType:moveUp',
        icon: 'el-icon-s-unfold',
        type: 2,
        level: 3,
        state: 1,
        sort: 0,
        remark: '',
        version: 0,
        createTime: '2019-10-26 11:15:48',
        updateTime: null,
        component: null,
        maxLevel: null,
        children: []
      },
      {
        id: 2011,
        name: '物品类型下移',
        parentId: 520,
        url: null,
        code: 'box:productType:moveDown',
        icon: 'el-icon-s-unfold',
        type: 2,
        level: 3,
        state: 1,
        sort: 0,
        remark: '',
        version: 0,
        createTime: '2019-10-26 11:15:48',
        updateTime: null,
        component: null,
        maxLevel: null,
        children: []
      },
      {
        id: 2012,
        name: '物品类型列表',
        parentId: 520,
        url: null,
        code: 'box:productType:list',
        icon: 'el-icon-s-unfold',
        type: 2,
        level: 3,
        state: 1,
        sort: 0,
        remark: '',
        version: 0,
        createTime: '2019-10-26 11:15:48',
        updateTime: null,
        component: null,
        maxLevel: null,
        children: []
      },
      {
        id: 2013,
        name: '同步物品',
        parentId: 520,
        url: null,
        code: 'box:boxSyncData:syncDataPositiveSeal',
        icon: 'el-icon-s-unfold',
        type: 2,
        level: 3,
        state: 1,
        sort: 0,
        remark: '',
        version: 0,
        createTime: '2019-10-26 11:15:48',
        updateTime: null,
        component: null,
        maxLevel: null,
        children: []
      }
    ]
  },
  {
    id: 80,
    name: '终端管理',
    parentId: 1,
    url: '/terminal',
    code: 'box:cabinetTerminal',
    icon: 'terminal',
    type: 1,
    level: 1,
    state: 1,
    sort: 0,
    remark: 'Terminal',
    version: 0,
    createTime: '2019-10-26 11:15:48',
    updateTime: null,
    component: null,
    maxLevel: 2,
    children: [
      {
        id: 1501,
        name: '智能柜终新增',
        parentId: 530,
        url: null,
        code: 'box:cabinetTerminal:add',
        icon: 'el-icon-s-unfold',
        type: 2,
        level: 3,
        state: 1,
        sort: 0,
        remark: '',
        version: 0,
        createTime: '2019-10-26 11:15:48',
        updateTime: null,
        component: null,
        maxLevel: null,
        children: []
      },
      {
        id: 1502,
        name: '智能柜终修改',
        parentId: 530,
        url: null,
        code: 'box:cabinetTerminal:edit',
        icon: 'el-icon-s-unfold',
        type: 2,
        level: 3,
        state: 1,
        sort: 0,
        remark: '',
        version: 0,
        createTime: '2019-10-26 11:15:48',
        updateTime: null,
        component: null,
        maxLevel: null,
        children: []
      },
      {
        id: 1503,
        name: '智能柜终端详情',
        parentId: 530,
        url: null,
        code: 'box:cabinetTerminal:view',
        icon: 'el-icon-s-unfold',
        type: 2,
        level: 3,
        state: 1,
        sort: 0,
        remark: '',
        version: 0,
        createTime: '2019-10-26 11:15:48',
        updateTime: null,
        component: null,
        maxLevel: null,
        children: []
      },
      {
        id: 1504,
        name: '智能柜终端删除',
        parentId: 530,
        url: null,
        code: 'box:cabinetTerminal:delete',
        icon: 'el-icon-s-unfold',
        type: 2,
        level: 3,
        state: 1,
        sort: 0,
        remark: '',
        version: 0,
        createTime: '2019-10-26 11:15:48',
        updateTime: null,
        component: null,
        maxLevel: null,
        children: []
      },
      {
        id: 1505,
        name: '智能柜终端列表',
        parentId: 530,
        url: null,
        code: 'box:cabinetTerminal:list',
        icon: 'el-icon-s-unfold',
        type: 2,
        level: 3,
        state: 1,
        sort: 0,
        remark: '',
        version: 0,
        createTime: '2019-10-26 11:15:48',
        updateTime: null,
        component: null,
        maxLevel: null,
        children: []
      },
      {
        id: 1506,
        name: '智能柜终端统计',
        parentId: 530,
        url: null,
        code: 'box:cabinetTerminal:statistics',
        icon: 'el-icon-s-unfold',
        type: 2,
        level: 3,
        state: 1,
        sort: 0,
        remark: '',
        version: 0,
        createTime: '2019-10-26 11:15:48',
        updateTime: null,
        component: null,
        maxLevel: null,
        children: []
      },
      {
        id: 1507,
        name: '智能柜终端下拉框',
        parentId: 530,
        url: null,
        code: 'box:cabinetTerminal:select',
        icon: 'el-icon-s-unfold',
        type: 2,
        level: 3,
        state: 1,
        sort: 0,
        remark: '',
        version: 0,
        createTime: '2019-10-26 11:15:48',
        updateTime: null,
        component: null,
        maxLevel: null,
        children: []
      }
    ]
  },
  {
    id: 90,
    name: '日志管理',
    parentId: 1,
    url: '/log',
    code: 'sys:log:manager',
    icon: 'log',
    type: 1,
    level: 1,
    state: 1,
    sort: 0,
    remark: 'Log',
    version: 0,
    createTime: '2019-10-26 11:18:40',
    updateTime: null,
    component: null,
    maxLevel: 3,
    children: [
      {
        id: 540,
        name: '开箱日志',
        parentId: 90,
        url: 'openlog',
        code: 'box:boxLog:second',
        icon: 'log',
        type: 1,
        level: 2,
        state: 1,
        sort: 0,
        remark: 'openLog',
        version: 0,
        createTime: '2019-10-26 11:18:40',
        updateTime: null,
        component: 'log/openlog',
        maxLevel: null,
        children: [
          {
            id: 1401,
            name: '开箱日志列表',
            parentId: 540,
            url: null,
            code: 'box:boxLog:page',
            icon: 'el-icon-s-custom',
            type: 2,
            level: 3,
            state: 1,
            sort: 0,
            remark: '',
            version: 0,
            createTime: '2019-10-26 11:18:40',
            updateTime: null,
            component: null,
            maxLevel: null,
            children: []
          }
        ]
      },
      {
        id: 541,
        name: '操作日志',
        parentId: 90,
        url: 'operatelog',
        code: 'box:boxFlowLog:second',
        icon: 'log',
        type: 1,
        level: 2,
        state: 1,
        sort: 0,
        remark: 'operatelog',
        version: 0,
        createTime: '2019-10-26 11:18:40',
        updateTime: null,
        component: 'log/operatelog',
        maxLevel: null,
        children: [
          {
            id: 1402,
            name: '操作日志列表',
            parentId: 541,
            url: null,
            code: 'sys:operation:log:page',
            icon: 'el-icon-s-custom',
            type: 2,
            level: 3,
            state: 1,
            sort: 0,
            remark: '',
            version: 0,
            createTime: '2019-10-26 11:18:40',
            updateTime: null,
            component: null,
            maxLevel: null,
            children: []
          }
        ]
      },
      {
        id: 542,
        name: '终端日志',
        parentId: 90,
        url: 'terminalLog',
        code: 'box:terminalLog:second',
        icon: 'log',
        type: 1,
        level: 2,
        state: 1,
        sort: 0,
        remark: 'terminal',
        version: 0,
        createTime: '2019-10-26 11:18:40',
        updateTime: null,
        component: 'log/terminalLog',
        maxLevel: null,
        children: [
          {
            id: 1403,
            name: '终端日志列表',
            parentId: 542,
            url: null,
            code: 'sys:terminal:log:page',
            icon: 'el-icon-s-custom',
            type: 2,
            level: 3,
            state: 1,
            sort: 0,
            remark: '',
            version: 0,
            createTime: '2019-10-26 11:18:40',
            updateTime: null,
            component: null,
            maxLevel: null,
            children: []
          }
        ]
      }
    ]
  },
  {
    id: 100,
    name: '部门与员工',
    parentId: 1,
    url: '/systems',
    code: 'user:management',
    icon: 'systems',
    type: 1,
    level: 1,
    state: 1,
    sort: 0,
    remark: 'Systems',
    version: 0,
    createTime: '2019-10-26 11:15:48',
    updateTime: null,
    component: null,
    maxLevel: 3,
    children: [
      {
        id: 550,
        name: '部门管理',
        parentId: 100,
        url: 'department',
        code: 'user:user:second',
        icon: 'systems',
        type: 1,
        level: 2,
        state: 1,
        sort: 0,
        remark: 'Department',
        version: 0,
        createTime: '2019-10-26 11:18:40',
        updateTime: null,
        component: 'systems/department',
        maxLevel: null,
        children: [
          {
            id: 1300,
            name: '部门新增',
            parentId: 550,
            url: null,
            code: 'user:department:add',
            icon: 'el-icon-s-custom',
            type: 2,
            level: 3,
            state: 1,
            sort: 0,
            remark: '',
            version: 0,
            createTime: '2019-10-26 11:18:40',
            updateTime: null,
            component: null,
            maxLevel: null,
            children: []
          },
          {
            id: 1301,
            name: '部门修改',
            parentId: 550,
            url: null,
            code: 'user:department:update',
            icon: 'el-icon-s-custom',
            type: 2,
            level: 3,
            state: 1,
            sort: 0,
            remark: '',
            version: 0,
            createTime: '2019-10-26 11:18:40',
            updateTime: null,
            component: null,
            maxLevel: null,
            children: []
          },
          {
            id: 1302,
            name: '部门删除',
            parentId: 550,
            url: null,
            code: 'user:department:delete',
            icon: 'el-icon-s-custom',
            type: 2,
            level: 3,
            state: 1,
            sort: 0,
            remark: '',
            version: 0,
            createTime: '2019-10-26 11:18:40',
            updateTime: null,
            component: null,
            maxLevel: null,
            children: []
          },
          {
            id: 1303,
            name: '部门详情',
            parentId: 550,
            url: null,
            code: 'user:department:info',
            icon: 'el-icon-s-custom',
            type: 2,
            level: 3,
            state: 1,
            sort: 0,
            remark: '',
            version: 0,
            createTime: '2019-10-26 11:18:40',
            updateTime: null,
            component: null,
            maxLevel: null,
            children: []
          },
          {
            id: 1304,
            name: '部门分页列表',
            parentId: 550,
            url: null,
            code: 'user:department:page',
            icon: 'el-icon-s-custom',
            type: 2,
            level: 3,
            state: 1,
            sort: 0,
            remark: '',
            version: 0,
            createTime: '2019-10-26 11:18:40',
            updateTime: null,
            component: null,
            maxLevel: null,
            children: []
          },
          {
            id: 1305,
            name: '部门列表',
            parentId: 550,
            url: null,
            code: 'user:department:list',
            icon: 'el-icon-s-custom',
            type: 2,
            level: 3,
            state: 1,
            sort: 0,
            remark: '',
            version: 1,
            createTime: '2019-10-26 11:18:40',
            updateTime: '2020-03-09 00:50:13',
            component: null,
            maxLevel: null,
            children: []
          },
          {
            id: 1306,
            name: '部门树形列表',
            parentId: 550,
            url: null,
            code: 'user:department:all:tree',
            icon: 'el-icon-s-custom',
            type: 2,
            level: 3,
            state: 1,
            sort: 0,
            remark: '',
            version: 0,
            createTime: '2019-10-26 11:18:40',
            updateTime: null,
            component: null,
            maxLevel: null,
            children: []
          },
          {
            id: 1307,
            name: '所有部门列表',
            parentId: 550,
            url: null,
            code: 'user:department:all:list',
            icon: 'el-icon-s-custom',
            type: 2,
            level: 3,
            state: 1,
            sort: 0,
            remark: '',
            version: 0,
            createTime: '2019-10-26 11:18:40',
            updateTime: null,
            component: null,
            maxLevel: null,
            children: []
          },
          {
            id: 1308,
            name: '部门排序移动',
            parentId: 550,
            url: null,
            code: 'user:department:move',
            icon: 'el-icon-s-custom',
            type: 2,
            level: 3,
            state: 1,
            sort: 0,
            remark: '',
            version: 0,
            createTime: '2019-10-26 11:18:40',
            updateTime: null,
            component: null,
            maxLevel: null,
            children: []
          }
        ]
      },
      {
        id: 551,
        name: '员工管理',
        parentId: 100,
        url: 'employee',
        code: 'user:userDepartment:second',
        icon: 'systems',
        type: 1,
        level: 2,
        state: 1,
        sort: 0,
        remark: 'Employee',
        version: 0,
        createTime: '2019-10-26 11:18:40',
        updateTime: null,
        component: 'systems/employee',
        maxLevel: null,
        children: [
          {
            id: 1001,
            name: '用户修改',
            parentId: 551,
            url: null,
            code: 'user:update',
            icon: 'el-icon-s-custom',
            type: 2,
            level: 3,
            state: 1,
            sort: 0,
            remark: '',
            version: 0,
            createTime: '2019-10-26 11:18:40',
            updateTime: null,
            component: null,
            maxLevel: null,
            children: []
          },
          {
            id: 1002,
            name: '用户删除',
            parentId: 551,
            url: null,
            code: 'user:delete',
            icon: 'el-icon-s-custom',
            type: 2,
            level: 3,
            state: 1,
            sort: 0,
            remark: '',
            version: 0,
            createTime: '2019-10-26 11:18:40',
            updateTime: null,
            component: null,
            maxLevel: null,
            children: []
          },
          {
            id: 1003,
            name: '用户详情',
            parentId: 551,
            url: null,
            code: 'user:info',
            icon: 'el-icon-s-custom',
            type: 2,
            level: 3,
            state: 1,
            sort: 0,
            remark: '',
            version: 0,
            createTime: '2019-10-26 11:18:40',
            updateTime: null,
            component: null,
            maxLevel: null,
            children: []
          },
          {
            id: 1004,
            name: '用户分页列表',
            parentId: 551,
            url: null,
            code: 'user:page',
            icon: 'el-icon-s-custom',
            type: 2,
            level: 3,
            state: 1,
            sort: 0,
            remark: '',
            version: 0,
            createTime: '2019-10-26 11:18:40',
            updateTime: null,
            component: null,
            maxLevel: null,
            children: []
          },
          {
            id: 1005,
            name: '用户修改密码',
            parentId: 551,
            url: null,
            code: 'user:update:password',
            icon: 'el-icon-s-custom',
            type: 2,
            level: 3,
            state: 1,
            sort: 0,
            remark: '',
            version: 0,
            createTime: '2019-10-26 11:18:40',
            updateTime: null,
            component: null,
            maxLevel: null,
            children: []
          },
          {
            id: 1006,
            name: '用户修改头像',
            parentId: 551,
            url: null,
            code: 'user:update:head',
            icon: 'el-icon-s-custom',
            type: 2,
            level: 3,
            state: 1,
            sort: 0,
            remark: '',
            version: 0,
            createTime: '2019-10-26 11:18:40',
            updateTime: null,
            component: null,
            maxLevel: null,
            children: []
          },
          {
            id: 1007,
            name: '用户重置密码',
            parentId: 551,
            url: null,
            code: 'user:reset:password',
            icon: 'el-icon-s-custom',
            type: 2,
            level: 3,
            state: 1,
            sort: 0,
            remark: '',
            version: 0,
            createTime: '2019-10-26 11:18:40',
            updateTime: null,
            component: null,
            maxLevel: null,
            children: []
          },
          {
            id: 1008,
            name: '用户列表',
            parentId: 551,
            url: null,
            code: 'user:list',
            icon: 'el-icon-s-custom',
            type: 2,
            level: 3,
            state: 1,
            sort: 0,
            remark: '',
            version: 0,
            createTime: '2019-10-26 11:18:40',
            updateTime: null,
            component: null,
            maxLevel: null,
            children: []
          },
          {
            id: 1009,
            name: '用户下拉框',
            parentId: 551,
            url: null,
            code: 'user:select',
            icon: 'el-icon-s-custom',
            type: 2,
            level: 3,
            state: 1,
            sort: 0,
            remark: '',
            version: 0,
            createTime: '2019-10-26 11:18:40',
            updateTime: null,
            component: null,
            maxLevel: null,
            children: []
          },
          {
            id: 1010,
            name: '禁止/开启登录',
            parentId: 551,
            url: null,
            code: 'user:login:switch',
            icon: 'el-icon-s-custom',
            type: 2,
            level: 3,
            state: 1,
            sort: 0,
            remark: '',
            version: 0,
            createTime: '2019-10-26 11:18:40',
            updateTime: null,
            component: null,
            maxLevel: null,
            children: []
          }
        ]
      },
      {
        id: 552,
        name: '角色与权限',
        parentId: 100,
        url: 'role',
        code: 'user:userRole:second',
        icon: 'systems',
        type: 1,
        level: 2,
        state: 1,
        sort: 0,
        remark: 'Role',
        version: 0,
        createTime: '2019-10-26 11:18:40',
        updateTime: null,
        component: 'systems/role',
        maxLevel: null,
        children: [
          {
            id: 1100,
            name: '角色新增',
            parentId: 552,
            url: null,
            code: 'user:role:add',
            icon: 'el-icon-s-custom',
            type: 2,
            level: 3,
            state: 1,
            sort: 0,
            remark: '',
            version: 0,
            createTime: '2019-10-26 11:18:40',
            updateTime: null,
            component: null,
            maxLevel: null,
            children: []
          },
          {
            id: 1101,
            name: '角色修改',
            parentId: 552,
            url: null,
            code: 'user:role:update',
            icon: 'el-icon-s-custom',
            type: 2,
            level: 3,
            state: 1,
            sort: 0,
            remark: '',
            version: 0,
            createTime: '2019-10-26 11:18:40',
            updateTime: null,
            component: null,
            maxLevel: null,
            children: []
          },
          {
            id: 1102,
            name: '角色删除',
            parentId: 552,
            url: null,
            code: 'user:role:delete',
            icon: 'el-icon-s-custom',
            type: 2,
            level: 3,
            state: 1,
            sort: 0,
            remark: '',
            version: 0,
            createTime: '2019-10-26 11:18:40',
            updateTime: null,
            component: null,
            maxLevel: null,
            children: []
          },
          {
            id: 1103,
            name: '角色详情',
            parentId: 552,
            url: null,
            code: 'user:role:info',
            icon: 'el-icon-s-custom',
            type: 2,
            level: 3,
            state: 1,
            sort: 0,
            remark: '',
            version: 0,
            createTime: '2019-10-26 11:18:40',
            updateTime: null,
            component: null,
            maxLevel: null,
            children: []
          },
          {
            id: 1105,
            name: '角色列表',
            parentId: 552,
            url: null,
            code: 'user:role:list',
            icon: 'el-icon-s-custom',
            type: 2,
            level: 3,
            state: 1,
            sort: 0,
            remark: '',
            version: 0,
            createTime: '2019-10-26 11:18:40',
            updateTime: null,
            component: null,
            maxLevel: null,
            children: []
          },
          {
            id: 1108,
            name: '分配权限',
            parentId: 552,
            url: null,
            code: 'user:permission:update',
            icon: 'el-icon-s-custom',
            type: 2,
            level: 3,
            state: 1,
            sort: 0,
            remark: '',
            version: 0,
            createTime: '2019-10-26 11:18:40',
            updateTime: null,
            component: null,
            maxLevel: null,
            children: []
          },
          {
            id: 1109,
            name: '添加成员',
            parentId: 552,
            url: null,
            code: 'user:role-user:update',
            icon: 'el-icon-s-custom',
            type: 2,
            level: 3,
            state: 1,
            sort: 0,
            remark: '',
            version: 0,
            createTime: '2019-10-26 11:18:40',
            updateTime: null,
            component: null,
            maxLevel: null,
            children: []
          }
        ]
      },
      {
        id: 554,
        name: '人脸管理',
        parentId: 100,
        url: 'faceManage',
        code: 'face:manage:second',
        icon: 'config',
        type: 1,
        level: 2,
        state: 1,
        sort: 0,
        remark: 'ConfigSetting',
        version: 0,
        createTime: '2019-10-26 11:18:40',
        updateTime: null,
        component: 'systems/faceManage',
        maxLevel: null,
        children: [
          {
            id: 2301,
            name: '人脸管理列表',
            parentId: 554,
            url: null,
            code: 'face:manage:list',
            icon: 'el-icon-s-unfold',
            type: 2,
            level: 3,
            state: 1,
            sort: 0,
            remark: '',
            version: 0,
            createTime: '2019-10-26 11:15:48',
            updateTime: null,
            component: null,
            maxLevel: null,
            children: []
          }
        ]
      }
    ]
  },
  {
    id: 110,
    name: '系统设置',
    parentId: 1,
    url: '/config',
    code: 'system:systemSetting',
    icon: 'config',
    type: 1,
    level: 1,
    state: 1,
    sort: 0,
    remark: 'Config',
    version: 0,
    createTime: '2019-10-26 11:15:48',
    updateTime: null,
    component: null,
    maxLevel: 2,
    children: [
      {
        id: 1601,
        name: '参数设置查询',
        parentId: 560,
        url: null,
        code: 'system:systemSetting:query',
        icon: 'el-icon-s-unfold',
        type: 2,
        level: 3,
        state: 1,
        sort: 0,
        remark: '',
        version: 0,
        createTime: '2019-10-26 11:15:48',
        updateTime: null,
        component: null,
        maxLevel: null,
        children: []
      },
      {
        id: 1602,
        name: '参数设置修改',
        parentId: 560,
        url: null,
        code: 'system:systemSetting:update',
        icon: 'el-icon-s-unfold',
        type: 2,
        level: 3,
        state: 1,
        sort: 0,
        remark: '',
        version: 0,
        createTime: '2019-10-26 11:15:48',
        updateTime: null,
        component: null,
        maxLevel: null,
        children: []
      }
    ]
  },
  {
    id: 130,
    name: '通知中心',
    parentId: 1,
    url: '/noticeCenter',
    code: 'notice:center',
    icon: 'config',
    type: 1,
    level: 1,
    state: 1,
    sort: 0,
    remark: 'Config',
    version: 0,
    createTime: '2019-10-26 11:15:48',
    updateTime: null,
    component: null,
    maxLevel: 3,
    children: [
      {
        id: 581,
        name: '消息模板',
        parentId: 130,
        url: 'msgTemplate',
        code: 'notice:msg:template',
        icon: 'config',
        type: 1,
        level: 2,
        state: 1,
        sort: 0,
        remark: 'ConfigSetting',
        version: 0,
        createTime: '2019-10-26 11:18:40',
        updateTime: null,
        component: 'noticeCenter/msgTemplate',
        maxLevel: null,
        children: [
          {
            id: 2202,
            name: '消息模板列表',
            parentId: 581,
            url: null,
            code: 'msg:template:list',
            icon: 'el-icon-s-unfold',
            type: 2,
            level: 3,
            state: 1,
            sort: 0,
            remark: '',
            version: 0,
            createTime: '2019-10-26 11:15:48',
            updateTime: null,
            component: null,
            maxLevel: null,
            children: []
          }
        ]
      },
      {
        id: 582,
        name: '推送渠道',
        parentId: 130,
        url: 'pushChannel',
        code: 'notice:push:channel',
        icon: 'config',
        type: 1,
        level: 2,
        state: 1,
        sort: 0,
        remark: 'ConfigSetting',
        version: 0,
        createTime: '2019-10-26 11:18:40',
        updateTime: null,
        component: 'noticeCenter/pushChannel',
        maxLevel: null,
        children: [
          {
            id: 2203,
            name: '推送渠道列表',
            parentId: 582,
            url: null,
            code: 'push:channel:list',
            icon: 'el-icon-s-unfold',
            type: 2,
            level: 3,
            state: 1,
            sort: 0,
            remark: '',
            version: 0,
            createTime: '2019-10-26 11:15:48',
            updateTime: null,
            component: null,
            maxLevel: null,
            children: []
          }
        ]
      },
      {
        id: 583,
        name: '消息日志',
        parentId: 130,
        url: 'msgLog',
        code: 'notice:msg:log',
        icon: 'config',
        type: 1,
        level: 2,
        state: 1,
        sort: 0,
        remark: 'ConfigSetting',
        version: 0,
        createTime: '2019-10-26 11:18:40',
        updateTime: null,
        component: 'noticeCenter/msgLog',
        maxLevel: null,
        children: [
          {
            id: 2204,
            name: '消息日志列表',
            parentId: 583,
            url: null,
            code: 'msg:log:list',
            icon: 'el-icon-s-unfold',
            type: 2,
            level: 3,
            state: 1,
            sort: 0,
            remark: '',
            version: 0,
            createTime: '2019-10-26 11:15:48',
            updateTime: null,
            component: null,
            maxLevel: null,
            children: []
          }
        ]
      },
      {
        id: 5546,
        name: '通知人管理',
        parentId: 130,
        url: 'receiverManage',
        code: 'notice:msg:receiver',
        icon: 'config',
        type: 1,
        level: 2,
        state: 1,
        sort: 0,
        remark: 'ConfigSetting',
        version: 0,
        createTime: '2022-08-26 11:18:40',
        updateTime: null,
        component: 'noticeCenter/receiverManage',
        maxLevel: null,
        children: []
      }
    ]
  }
]
