const xieyi = `<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; font-size: 12pt;">更新日期：2023年05月06日</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; font-size: 16px;">生效日期：2023年05月06日</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><strong><span style="font-family: 宋体; font-size: 12pt;">一、声明与承诺</span></strong></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">（一）本服务条款是您与上海建业信息科技股份有限公司（</span><span style="font-family: 宋体; color: #222222; font-size: 12pt;">以</span><span style="font-family: 宋体; color: #222222; font-size: 12pt;">下</span><span style="font-family: 宋体; color: #222222; font-size: 12pt;">简</span><span style="font-family: 宋体; color: #222222; font-size: 12pt;">称</span><span style="font-family: 宋体; color: #222222; font-size: 12pt;">&ldquo;</span><span style="font-family: 宋体; color: #222222; font-size: 12pt;">建业科技</span><span style="font-family: 宋体; color: #222222; font-size: 12pt;">&rdquo;</span><span style="font-family: 宋体; color: #222222; font-size: 12pt;">）之间的协议。在本服务创建账户并使用之前，您必须首先同意此条款。</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">（二）您同意，本公司有权随时对本协议内容进行单方面的变更，无需另行单独通知您；若您在本协议内容公告变更后继续使用本服务，表示您已充分阅读、理解并接受修改后的协议内容，也将遵循修改后的协议内容使用本服务；若您不同意修改后的协议内容，您应</span><span style="font-family: 宋体; color: #222222; font-size: 12pt;">立即</span><span style="font-family: 宋体; color: #222222; font-size: 12pt;">停止使用本服务。</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;"><span style="font-family: 宋体;">（三）您保证，在您同意接受本协议并注册成为建业科技用户时，您已经年满</span><span style="font-family: 宋体;">16周岁并具备完全的民事行为能力，或者您是在中国大陆地区依法设立并合法开展经营活动或其他业务的法人或其他组织；本协议内容不受您所属国家或地区法律的排斥。在您注册成为建业科技试用申请用户时或在此后任何时间不具备前述条件的，您应立即终止注册或停止使用本服务。您在使用建业科技产品相关服务时，应自行判断对方是否是完全民事行为能力人，且确定他提供的信息和他本人对应，并自行决定是否与对方完成系统操作等，且您应自行承担与此相关的所有风险。本平台不承担因对方身份确认失误而造成的损失。</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">（四）您保证，在您同意接受本协议并注册成为建业科技试用申请用户时，即表示您认可使用建业科技网站作为缔约方式，认可您在建业科技网站上的所有操作都是您个人意愿的表示。</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">（五）您同意，若您使用建业科技产品服务，本公司有权获取您的联系方式、个人和企业的身份信息。</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">（六）您同意，若您使用建业科技产品服务，本公司有权对您输入的个人身份信息，通过征信机构及其他具有国家认可资质的数据服务提供商进行进一步正确性验证。</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">（七）您确认并知悉，建业科技产品服务不适用于以下内容：</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">1、违反法律、行政法相关内容</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">2、涉及商业机密等内容</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt;"><span style="font-family: 宋体; color: #222222; font-size: 13.5pt;">&nbsp;</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><strong><span style="font-family: 宋体; font-size: 12pt;">二、定义及解释</span></strong></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;"><span style="font-family: 宋体;">建业科技产品试用申请账户（或</span><span style="font-family: 宋体;">&ldquo;该账户&rdquo;）：是本平台向您提供的唯一编号。您可自行为该账户设置密码，并用以操作建业科技系统，您需使用本人手机号码或者电子邮箱，或者本公司允许的其它方式，作为登录手段登录建业科技产品使用账户。</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;"><span style="font-family: 宋体;">企业用户：指购买并部署了建业科技产品并对这个产品有管理权限的个人或组织，包括但不限于法人、政府机构、其他组织、合伙或个体工商户等（下称</span><span style="font-family: 宋体;">&ldquo;企业用户&rdquo;）；&nbsp;企业用户可以通过建业科技系统创建其工作平台，并开通账号邀请相关人加入其工作平台成为其最终用户。</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">企业用户管理员：指经企业用户指定，拥有系统后台操作权限的个人；企业用户管理员可以一人或多人。</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;"><span style="font-family: 宋体;">个人用户：指被企业用户邀请并通过企业用户为其在后台开通的账号登录使用建业科技系统的个人用户，以下称</span><span style="font-family: 宋体;">&ldquo;您&rdquo;或&ldquo;最终用户&rdquo;。</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">个人信息：指以电子或者其他方式记录的能够单独或者与其他信息结合识别特定自然人身份或者反映特定自然人活动情况的各种信息。</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">个人敏感信息：指一旦泄露、非法提供或滥用可能危害人身和财产安全，极易导致个人名誉、身心健康受到损害或歧视性待遇等的个人信息，包括身份证件号码、个人生物识别信息、通信记录和内容、财产信息、行踪轨迹、健康生理信息、交易信息等。</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt;"><span style="font-family: 宋体; color: #222222; font-size: 13.5pt;">&nbsp;</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><strong><span style="font-family: 宋体; font-size: 12pt;">三、建业科技提供产品体系</span></strong></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">印章智慧管理平台：章管家</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">便携式智能印章；</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">智能用印工作台；</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">电子签约服务；</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt;"><span style="font-family: 宋体; color: #222222; font-size: 13.5pt;">&nbsp;</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><strong><span style="font-family: 宋体; font-size: 12pt;">四、建业科技账户</span></strong></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">（一）注册相关</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;"><span style="font-family: 宋体;">除本协议另有规定或相关产品另有规则外，您须在本网站及</span><span style="font-family: 宋体;">/或无线客户端注册并取得本公司提供给您的建业科技账户，并且按照本公司要求提供相关信息完成激活后方可使用本服务。您同意：</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">1、按照本公司要求准确提供并在取得该账户后及时更新您正确、最新及完整的身份信息及相关资料。若本公司有合理理由怀疑您提供的身份信息及相关资料错误、不实、过时或不完整的，本公司有权暂停或终止向您提供部分或全部建业科技服务。本公司对此不承担任何责任，您将承担因此产生的任何直接或间接支出。若因国家法律法规、部门规章或监管机构的要求，本公司需要您补充提供任何相关资料时，如您不能及时配合提供，本公司有权暂停或终止向您提供部分或全部建业科技服务。</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">2、您应当准确提供并及时更新您提供的电子邮件地址、联系电话等联系方式，以便本公司与您进行及时、有效联系。您应完全独自承担因通过这些联系方式无法与您取得联系而导致的您在使用本服务过程中遭受的任何损失或增加任何费用等不利后果。您理解并同意，您有义务保持您提供的联系方式的有效性，如有变更需要更新的，您应按本公司的要求进行操作。</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">3、您应及时更新资料（包括但不限于身份证、护照等证件或其他身份证明文件、联系方式、作为建业科技登录名的邮箱或手机号码、与建业科技账户绑定的邮箱、手机号码等），否则建业科技有权将建业科技登录名、建业科技账户绑定的邮箱、手机号码开放给其他用户注册或使用。因您未及时更新资料导致的一切后果，均应由您自行承担，该后果包括但不限于导致本服务无法提供或提供时发生任何错误、账户及账户内信息被别人盗用，且您不得将此作为拒绝执行协议的理由。</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">4、您确认，只有您本人可以使用您的建业科技账户。在您决定不再使用该账户时，您应按照本条（四）的规定向本公司申请注销该账户。您同意，若您丧失全部或部分民事权利能力或民事行为能力，本公司有权根据有效法律文书（包括但不限于生效的法院判决、生效的遗嘱等）或本公司认可的其他资料处置您建业科技账户内的资料。</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">5、若您为个人用户，您确认，本公司有权在必要时要求核对您的有效身份证件或其他必要文件，您应积极配合，否则本公司有权限制或停止向您提供部分或全部建业科技服务：</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">A、您要求变更身份信息或您身份信息已过有效期的；</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">B、本公司认为您的使用行为或使用情况出现异常的；</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">C、本公司认为您的身份资料存在疑点或本公司在向您提供服务的过程中认为您已经提供的身份资料存在疑点的；</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">（二）账户安全</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">您将对使用该账户或密码进行的一切操作及言论负完全的责任，您同意：</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">1、除相关产品另有规则外，本公司可以通过您的建业科技登录名和密码或者本公司认可的其他方式识别您的身份，您应当对该密码、身份信息等进行妥善保管，对于因密码、身份信息、校验码等泄露所致的损失由您自行承担。您保证不向其他任何人泄露您的建业科技登录名及密码、校验码以及身份信息等，亦不使用其他任何人的建业科技登录名及密码。本公司亦可能通过本服务应用您使用的其他产品或设备识别您的指示，您应当妥善保管处于您或应当处于您掌控下的这些产品或设备，对于这些产品或设备遗失所致的任何损失，由您自行承担。</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">2、基于计算机端、手机端以及使用其他电子设备的用户使用习惯，我们可能在您使用具体产品时设置不同的账户登录模式及采取不同的措施识别您的身份。</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">3、您同意，（a）如您发现有他人冒用或盗用您的建业科技登录名及密码或任何其他未经合法授权之情形，或发生与建业科技账户关联的手机或其他设备遗失或其他可能危及到建业科技账户安全情形时，应立即以有效方式通知本公司，向本公司申请暂停相关服务，以保障您的合法权益；及（b）确保您在持续登录建业科技网站时段结束时，以正确步骤离开网站。本公司不能也不会对因您未能遵守本款约定而发生的任何损失、损毁及其他不利后果负责。您理解本公司对您的请求采取行动需要合理期限，在此之前，本公司对已执行的指令及（或）所导致的您的损失不承担任何责任。</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">4、除非您本人书面提出申请或者另有法律规定或经司法裁判，且征得本公司同意，否则您的建业科技登录名及密码、建业科技账户不得以任何方式转让、赠与或继承（相关的财产权益除外）。</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">5、您使用本服务时同意并认可，可能系统问题造成本服务无法提供，对此本公司不承担任何责任。</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">6、您同意，基于运行安全的需要，本公司可以暂时停止提供或者限制本服务部分功能，或提供新的功能，在任何功能减少、增加或者变化时，只要您仍然使用本服务，表示您仍然同意本协议或者变更后的协议。</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">7、本公司有权了解您使用本公司产品或服务的真实背景及目的，您应如实提供本公司所需的真实、全面、准确的信息。如果本公司有合理理由怀疑您提供虚假信息的，本公司有权暂时或永久限制您所使用的产品或服务的部分或全部功能，并通过邮件或者站内信或客户端通知等方式通知您，您应及时予以关注。</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">8、您同意，本公司有权按照包括但不限于公安机关、检察机关、法院、海关、税务机关等司法机关、行政机关、军事机关的要求对您的个人信息及在建业科技账户等进行查询、冻结或其他操作。</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">（三）注销相关</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">在需要终止使用本服务时，您可以申请注销您的建业科技账户，您同意：</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">1、您所申请注销的建业科技账户应当是您依照本协议的约定注册并由本公司提供给您本人的账户。您应当依照本公司规定的程序进行建业科技账户注销。</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">2、建业科技账户注销将导致本公司终止为您提供本服务，本协议约定的双方的权利义务终止（依本协议其他条款另行约定不得终止的或依其性质不能终止的除外），同时还可能对于该账户产生如下结果：</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">A、任何您的个人使用信息都将无法查看；</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">B、任何您的使用过程中产生的附属文档都将无法查看，您可以在注销之前进行保存。</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">C、注销完成后，本公司无法对您之前留存下来的任何信息提供鉴权，公证等服务</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">3、您可以通过人工的方式申请注销建业科技账户。</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">4、您申请注销的建业科技账户应当处于正常状态，即您的建业科技账户的账户信息和用户信息是最新、完整、正确的，且该账户可以使用所有建业科技服务功能。账户信息或用户信息过时、缺失、不正确的账户或被暂停或终止提供服务的账户不能被申请注销。</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">5、您申请注销的建业科技账户应当不存在任何由于该账户被注销而导致的未了结的合同关系与其他基于该账户的存在而产生或维持的权利义务，及本公司认为注销该账户会由此产生未了结的权利义务而产生纠纷的情况。</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">6、如果您申请注销的建业科技账户一旦注销成功，将不再予以恢复。</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">7、您理解并同意，如您在建业科技网站有欺诈、虚假信息、侵犯他人合法权益或其他严重违反建业科技网站规则或者中华人民共和国法律的行为的，本公司有权</span><span style="font-family: 宋体; color: #222222; font-size: 12pt;">不通知您即</span><span style="font-family: 宋体; color: #222222; font-size: 12pt;">注销您名下的全部或部分建业科技登录名，您将不能再登录建业科技网站，所有网站的服务将同时终止。</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt;"><span style="font-family: 宋体; color: #222222; font-size: 13.5pt;">&nbsp;</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><strong><span style="font-family: 宋体; font-size: 12pt;">五、建业科技服务使用规则</span></strong></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">为有效保障您使用本服务时的合法权益，您理解并同意接受以下规则：</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">（一）一旦您使用本服务，您即不可撤销地授权本公司在您及（或）您指定人符合指定条件或状态时，向您的合作伙伴发送操作申请并执行对应的操作。</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;"><span style="font-family: 宋体;">（二）本公司通过以下方式接受来自您的指令：</span><span style="font-family: 宋体;">A、您在本网站或其他可使用本服务的网站或软件上通过以您的建业科技账户名及密码或数字证书等安全产品登录建业科技账户并依照本服务预设流程所修改或确认的使用状态或指令；B、您通过您注册时作为该账户名称或者与该账户绑定的手机或其他专属于您的通讯工具（以下合称该手机）号码向本公司发送的信息（短信或电话等）回复；C、您通过您注册时作为该账户名称或者与该账户名称绑定的其他硬件、终端、软件、代号、编码、代码、其他账户名等有形体或无形体向本公司发送的信息（如本方式所指有形体或无形体具备与该手机接受信息相同或类似的功能，以下第五条第（四）、（五）、（六）项和第六条第（三）项涉及该手机的条款同样适用于本方式）；D、通过识别您的指纹、人脸等生物特征；E、本公司与您约定或本公司认可的其他方式。无论您通过以上何种方式向本公司发出指令，都不可撤回或撤销，且成为本公司代理您支付或收取款项或进行其他操作的唯一指令，视为您本人的指令，您应当自己对本公司忠实执行上述指令产生的任何结果承担责任。本协议所称绑定，指您的建业科技账户与本条上述所称有形体或无形体存在对应的关联关系，这种关联关系使得建业科技服务的某些服务功能得以实现，且这种关联关系有时使得这些有形体或无形体能够作为本公司对您的建业科技账户的识别和认定依据。</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">（三）您确认，您在网站上的任何操作以及因为操作导致的结果都具备法律效力。</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">本服务即表示您同意接受本服务的相关规则。您了解并同意本公司有权单方修改服务的相关规则，而无须征得您的同意，服务规则应以您使用服务时的页面提示（或发送到该手机的短信或电话或客户端通知等）为准，您同意并遵照服务规则是您使用本服务的前提。</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">1、在使用本服务时，若您的操作未遵从本服务条款或网站说明、系统页面中之操作提示、规则），则本公司有权拒绝为您的操作提供相关服务，且本公司不承担损害赔偿责任。</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">2、因您的过错导致的任何损失由您自行承担，该过错包括但不限于：不按照提示操作，未及时进行操作，遗忘或泄漏密码、校验码等，密码被他人破解，您使用的计算机或其他硬件、终端等被他人侵入或丢失，或您使用的软件被他人侵入，或者您的生物特征被他人利用。</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">（十二）服务费用</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">1、在您使用本服务时，本公司有权依照事先约定的服务协议向您收取服务费用。本公司拥有制订及调整服务费之权利，具体服务费用以您使用本服务时本网站或客户端、产品页面上所列之收费方式公告或您与本公司达成的其他书面协议为准。</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">2、除非另有说明或约定，您同意本公司有权自您委托本公司代收或代付的账户余额或者其他资产中直接扣除上述服务费用。</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;"><span style="font-family: 宋体;">（十三）您认可建业科技账户的使用记录等数据等均以本公司系统记录的数据为准。如您对该等数据存有异议的，应自您账户数据发生变动之日起</span><span style="font-family: 宋体;">30日内向本公司提出</span></span><span style="font-family: 宋体; color: #222222; font-size: 12pt;">书面</span><span style="font-family: 宋体; color: #222222; font-size: 12pt;">异议，并提供相关证据供本公司核实。</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt;"><span style="font-family: 宋体; color: #222222; font-size: 13.5pt;">&nbsp;</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><strong><span style="font-family: 宋体; font-size: 12pt;">六、建业科技服务使用限制</span></strong></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">（一）您在使用本服务时应遵守中华人民共和国相关法律法规、您所在国家或地区之法令及相关国际惯例，不将本服务用于任何非法目的，也不以任何非法方式使用本服务。</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">（二）您不得利用本服务从事侵害他人合法权益之行为，否则本公司有权拒绝提供本服务，且您应承担所有相关法律责任，因此导致本公司或本公司雇员或其他方受损的，您应承担赔偿责任。上述行为包括但不限于：</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">1、侵害他人名誉权、隐私权、商业秘密、商标权、著作权、专利权等合法权益。</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">2、违反依法定或约定之保密义务。</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">3、冒用他人名义使用本服务。</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">4、从事不法行为，如洗钱、恐怖融资、贩卖枪支、毒品、禁药、盗版软件、黄色淫秽物品、其他本公司认为不得使用本服务进行的操作等。</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">5、提供赌博资讯或以任何方式引诱他人参与赌博。</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">6、非法使用他人账户。</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">7、从事任何可能含有电脑病毒或是可能侵害本服务系统、资料之行为。</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">8、其他本公司有正当理由认为不适当之行为。</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">（三）您理解并同意，本公司不对因下述任一情况导致的任何损害赔偿承担责任，包括但不限于利润、商誉、使用、数据等方面的损失或其他无形损失的损害赔偿（无论本公司是否已被告知该等损害赔偿的可能性）：</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">1、本公司有权基于单方判断，包含但不限于本公司认为您已经违反本协议的明文规定及精神，对您名下的全部或部分建业科技账户暂停、中断或终止向您提供本服务或其任何部分，并移除您的资料。</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">2、本公司在发现异常操作或合理怀疑操作有疑义或有违反法律规定或本协议约定之虞时，有权不经通知先行暂停或终止您名下全部或部分建业科技账户的使用（包括但不限于对这些账户采取取消操作等限制措施），并拒绝您使用本服务之部分或全部功能，并通过邮件或站内信或客户端通知等方式通知您，您应及时予以关注。</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">3、您理解并同意，存在如下情形时，本公司有权对您名下建业科技账户暂停或终止提供全部或部分建业科技服务，且有权限制您所使用的产品或服务的部分或全部功能（包括但不限于对这些账户采取取消操作等限制措施），并通过邮件或站内信或者客户端通知等方式通知您，您应及时予以关注：</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">1）根据本协议的约定：</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">2）根据法律法规及法律文书的规定：</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">3）根据有权机关的要求：</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">4）您使用建业科技服务的行为涉嫌违反国家法律法规及行政规定的：</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">5）本公司基于单方面合理判断认为账户操作、资金进出等存在异常时：</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">6）本公司依据自行合理判断认为可能产生风险的：</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">7）您在参加市场活动时有批量注册账户、刷信用及其他舞弊等违反活动规则、违反诚实信用原则的：</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">8）您遭到他人投诉，且对方已经提供了一定证据的：</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">9）您可能错误地将他人账户进行了实名制或实名认证的。</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">如您申请恢复服务、解除上述止付或限制，您应按本公司要求如实提供相关资料及您的身份证明以及本公司要求的其他信息或文件，以便本公司进行核实，且本公司有权依照自行判断来决定是否同意您的申请。您应充分理解您的申请并不必然被允许。您拒绝如实提供相关资料及身份证明的，或未通过本公司审核的，则您确认本公司有权长期对该等账户停止提供服务且长期限制该等产品或者服务的部分或全部功能。</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">4、在本公司认为该等异常已经得到合理解释或有效证据支持或未违反国家相关法律法规及部门规章的情况下，最晚将于得到解释之日起的30个日历天内解除限制。但本公司有进一步理由相信该等异常仍可能对您或其他用户或本公司造成损失的情形除外，包括但不限于：</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">1）收到针对该等异常的投诉：</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">2）您已经实质性违反了本协议或另行签署的协议，且我们基于保护各方利益的需要必须继续止付款项或暂停执行指令：</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">3）您虽未违反国家相关法律法规及部门规章规定，但该等使用涉及本公司限制合作的行业类目或商品，包括但不限于通过本公司的产品或服务从事类似金字塔或矩阵型的高额返利业务模式。</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">5、在本公司合理认为有必要时，本公司无需事先通知即可终止提供本服务，并暂停、关闭或删除您名下全部或部分建业科技账户及这些账户中所有相关资料及档案。</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">（四）如您需要注销您的建业科技账户，应先经本公司审核同意。本公司注销该账户，即表明本公司与您之间的协议已终止，但您仍应对您使用本服务期间的行为承担可能的违约或损害赔偿责任，同时本公司仍可保有您的相关信息。</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt;"><span style="font-family: 宋体; color: #222222; font-size: 13.5pt;">&nbsp;</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><strong><span style="font-family: 宋体; font-size: 12pt;">七、系统中断或故障</span></strong></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">本公司系统因下列状况无法正常运作，使您无法使用各项服务时，本公司不承担损害赔偿责任，该状况包括但不限于：</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">（一）本公司在本网站公告之系统停机维护期间。</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">（二）电信设备出现故障不能进行数据传输的。</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">（三）因台风、地震、海啸、洪水、停电、战争、恐怖袭击等不可抗力之因素，造成本公司系统障碍不能执行业务的。</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">（四）由于黑客攻击、电信部门技术调整或故障、网站升级、银行方面的问题等原因而造成的服务中断或者延迟。</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt;"><span style="font-family: 宋体; color: #222222; font-size: 13.5pt;">&nbsp;</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><strong><span style="font-family: 宋体; font-size: 12pt;">八、责任范围及责任限制</span></strong></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">（一）本公司仅对本协议中列明的责任承担范围负责。</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">（二）您明确因操作所产生的任何风险应由您与操作对方承担。</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">（三）本公司用户信息是由用户本人自行提供的，本公司无法保证该信息之准确、及时和完整，您应对您的判断承担全部责任。</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;"><span style="font-family: 宋体;">（四）本公司不对操作标的及本服务提供任何形式的保证，包括但不限于以下事项</span><span style="font-family: 宋体;">:</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">1、本服务符合您的需求。</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">2、本服务不受干扰、及时提供或免于出错。</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">3、您经由本服务购买或取得之任何产品、服务、资讯或其他资料符合您的期望。</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">（五）本服务之合作单位，所提供之服务品质及内容由该合作单位自行负责。</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">（六）您经由本服务之使用下载或取得任何资料，应由您自行考量且自负风险，因资料之下载而导致您电脑系统之任何损坏或资料流失，您应负完全责任。</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">（七）您自本公司及本公司工作人员或经由本服务取得之建议和资讯，无论其为书面或口头形式，均不构成本公司对本服务之保证。</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">（八）在法律允许的情况下，本公司对于与本协议有关或由本协议引起的任何间接的、惩罚性的、特殊的、派生的损失（包括业务损失、收益损失、利润损失、商誉损失、使用数据或其他经济利益的损失），不论是如何产生的，也不论是由对本协议的违约（包括违反保证）还是由侵权造成的，均不负有任何责任，即使事先已被告知此等损失的可能性。另外即使本协议规定的排他性救济没有达到其基本目的，也应排除本公司对上述损失的责任。</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">（九）您充分知晓并同意本公司可能同时为您及您的对手方提供本服务，您同意对本公司可能存在的该等行为予以明确豁免，并不得以此来主张本公司在提供本服务时存在法律上的瑕疵。</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">（十）除本协议另有规定或本公司另行同意外，您对本公司的委托及向本公司发出的指令均不可撤销。</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt;"><span style="font-family: 宋体; color: #222222; font-size: 13.5pt;">&nbsp;</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><strong><span style="font-family: 宋体; font-size: 12pt;">九、商标、知识产权、专利的保护</span></strong></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">（一）本公司及关联公司所有系统及本网站上所有内容，包括但不限于著作、图片、档案、资讯、资料、网站架构、网站画面的安排、网页设计，均由本公司或本公司关联公司依法拥有其知识产权，包括但不限于商标权、专利权、著作权、商业秘密等。</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">（二）非经本公司或本公司关联企业书面同意，任何人不得擅自使用、修改、复制、公开传播、改变、散布、发行或公开发表本网站程序或内容。</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">（三）尊重知识产权是您应尽的义务，如有违反，您应承担损害赔偿责任。</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt;"><span style="font-family: 宋体; color: #222222; font-size: 13.5pt;">&nbsp;</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><strong><span style="font-family: 宋体; font-size: 12pt;">十、法律适用与管辖</span></strong></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><strong><span style="font-family: 宋体; font-size: 12pt;">本协议之效力、解释、变更、执行与争议解决均适用中华人民共和国法律，没有相关法律规定的，参照通用国际商业惯例和（或）行业惯例。因本协议产生之争议，均应依照中华人民共和国法律予以处理，并由</span></strong><strong><span style="font-family: 宋体; font-size: 12pt;">本公司住所</span></strong><strong><span style="font-family: 宋体; font-size: 12pt;">地人民法院管辖。</span></strong></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><strong><span style="font-family: 宋体; font-size: 12pt;">&nbsp;</span></strong></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; text-indent: 24pt; line-height: 21pt;"><strong><span style="font-family: 宋体; color: #ff0000; font-size: 12pt;">我已清楚知晓并认可本协议的内容，特别是本协议中排除我方主要权利、加重我方责任及减轻或免除贵司责任的条款。我方确认对本协议的条款均无异议。</span></strong></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; text-align: justify; font-family: 等线; font-size: 10.5pt;"><span style="font-size: 10.5pt;">&nbsp;</span></p>`

export default xieyi
