const yinsi = `<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; font-size: 12pt;">更新日期：2023年05月06日</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; font-size: 16px;">生效日期：2023年05月06日</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;">&nbsp;</p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><strong><span style="font-family: 宋体; font-size: 12pt;">欢迎您使用我们的产品和服务！</span></strong></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><strong><span style="font-family: 宋体; color: #222222; font-size: 12pt;"><span style="font-family: 宋体;">我们非常重视对您的个人</span><span style="font-family: 宋体;">/企业隐私保护，我们将按照本政策收集、使用、共享和保护您的个人/企业信息，</span></span></strong><strong><span style="font-family: Helvetica; font-size: 12pt;"><span style="font-family: 宋体;">本隐私政策适用于您对</span></span></strong><strong><span style="font-family: 宋体; font-size: 12pt;">上海建业信息科技股份有限公司</span></strong><strong><span style="font-family: Helvetica; font-size: 12pt;"><span style="font-family: 宋体;">（以下亦称</span><span style="font-family: Helvetica;">&ldquo;</span><span style="font-family: 宋体;">我们</span><span style="font-family: Helvetica;">&rdquo;</span><span style="font-family: 宋体;">或</span><span style="font-family: Helvetica;">&ldquo;</span></span></strong><strong><span style="font-family: 宋体; font-size: 12pt;">建业科技</span></strong><strong><span style="font-family: Helvetica; font-size: 12pt;"><span style="font-family: Helvetica;">&rdquo;</span><span style="font-family: 宋体;">）旗下产品的访问和使用留存的信息</span></span></strong><span style="font-family: 宋体; color: #222222; font-size: 12pt;">。</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;"><span style="font-family: 宋体;">我们收集、使用、共享和保护您的个人</span><span style="font-family: 宋体;">/企业信息，是在遵守国家法律法规规定的前提下，出于向您提供建业科技的产品及服务并不断提升产品及服务质量的目的，以及保障您的账户安全。 使用本服务，即表示您同意建业科技合法收集和使用有关您及您所使用本服务的技术性或诊断性信息。收集到的些信息将用于改进网页的内容，提升我们的服务品质。</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;"><span style="font-family: 宋体;">请在使用我们的产品</span><span style="font-family: 宋体;">(或服务)前，仔细阅读并了解本《隐私政策》。</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt;"><span style="font-family: 宋体; color: #222222; font-size: 13.5pt;">&nbsp;</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;"><span style="font-family: 宋体;">本政策将帮助您了解以下内容</span><span style="font-family: 宋体;">:</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;"><span style="font-family: 宋体;">一、我们如何收集和使用您的个人</span><span style="font-family: 宋体;">/企业信息</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;"><span style="font-family: 宋体;">二、我们如何使用</span><span style="font-family: 宋体;">Cookie和同类技术</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;"><span style="font-family: 宋体;">三、我们如何共享、转让和公开披露您的个人</span><span style="font-family: 宋体;">/企业信息</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;"><span style="font-family: 宋体;">四、我们如何保护您的个人</span><span style="font-family: 宋体;">/企业信息</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">五、您的权利</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">六、我们如何处理儿童的个人信息</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">七、本政策如何更新</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">八、如何联系我们</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt;"><span style="font-family: 宋体; color: #222222; font-size: 13.5pt;">&nbsp;</span></p>
<p class="15" style="margin-left: 24.75pt; text-indent: -24.75pt; line-height: 21pt;"><span style="font-family: 宋体; font-weight: bold; font-size: 12pt;">一、&nbsp;</span><strong><span style="font-family: 宋体; font-size: 12pt;"><span style="font-family: 宋体;">我们如何收集和使用您的个人</span><span style="font-family: 宋体;">/企业信息</span></span></strong></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; font-size: 12pt;"><span style="font-family: 宋体;">我们会出于本政策所述的以下目的，收集和使用您的个人</span><span style="font-family: 宋体;">/企业信息:</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">（一）帮助您成为我们的注册用户</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">为成为我们的注册用户，以便我们为您提供产品服务，您需要提供姓名、手机号码、电子邮箱地址以及您的公司名称</span><span style="font-family: 宋体; color: #222222; font-size: 12pt;">等信息</span><span style="font-family: 宋体; color: #222222; font-size: 12pt;">。如果您仅需使用浏览基本服务，您不需要注册成为我们的用户及提供上述信息。</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">（二）向您提供产品或服务</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;"><span style="font-family: 宋体;">当您使用建业科技产品服务时，为保障您正常使用我们的服务，我们会收集您的设备型号、操作系统、设备标识符、</span><span style="font-family: 宋体;">IP地址、建业科技软件版本号、操作日志</span></span><span style="font-family: 宋体; color: #222222; font-size: 12pt;">及位置等</span><span style="font-family: 宋体; color: #222222; font-size: 12pt;">信息</span><span style="font-family: 宋体; color: #222222; font-size: 12pt;">，</span><span style="font-family: 宋体; color: #222222; font-size: 12pt;">需要您授权开通位置、相机等权限</span><span style="font-family: 宋体; color: #222222; font-size: 12pt;"><span style="font-family: 宋体;">，这类信息是为提供服务必须收集的基础信息。</span> <span style="font-family: 宋体;">请注意，单独的设备信息、日志信息是无法识别特定自然人身份的信息。如果我们将这类非个人信息与其他信息结合用于识别特定自然人身份，或者将其与个人信息结合使用，则在结合使用期间，这类非个人信息将被视为个人信息，除取得您授权或法律法规另有规定外，我们会将该类个人信息做匿名化、去标识化处理。</span> <span style="font-family: 宋体;">当您与我们联系时，我们可能会保存您的通信</span><span style="font-family: 宋体;">/通话记录和内容或您留下的联系方式信息，以便与您联系或帮助您解决问题，或记录相关问题的处理方案及结果。</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">（三）其他用途</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">我们将信息用于本政策未载明的其他用途，或者将基于特定目的收集而来的信息用于其他目的时，会事先征求您的同意。</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">（四）征得授权同意的例外</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;"><span style="font-family: 宋体;">根据相关法律法规规定，以下情形中收集您的个人</span><span style="font-family: 宋体;">/企业信息无需征得您的授权同意:</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">1、与国家安全、国防安全有关的;</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">2、与公共安全、公共卫生、重大公共利益有关的;</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">3、与犯罪侦查、起诉、审判和判决执行有关的;</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">4、出于维护个人信息主体或其他个人的生命、财产重大合法权益但又很难得到您本人同意的;</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">5、所收集的个人/企业信息是您自行向社会公众公开的;</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">6、从合法公开披露的信息中收集个人/企业信息的，如合法的新闻报道、政府信息公开渠道;</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">7、用于维护所提供的产品或服务的安全稳定运行所必需的;</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">8、法律法规规定的其他情形。</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">&nbsp;</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt;"><span style="font-family: 宋体; color: #222222; font-size: 13.5pt;">&nbsp;</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><strong><span style="font-family: 宋体; font-size: 12pt;"><span style="font-family: 宋体;">二、我们如何使用</span><span style="font-family: 宋体;">Cookie和同类技术</span></span></strong></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;"><span style="font-family: 宋体;">为确保网站正常运转、为您获得更轻松的访问体验，我们会在您的计算机或移动设备上存储名为</span><span style="font-family: 宋体;">Cookie的小数据文件。Cookie通常包含标识符、站点名称以及一些号码和字符。我们不会在Cookie里面存储与个人身份或隐私相关的信息。</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;"><span style="font-family: 宋体;">您可根据自己的偏好管理或删除</span><span style="font-family: 宋体;">Cookie。有关详情，请参见AboutCookies.org。您可以清除计算机上保存的所有Cookie，大部分网络浏览器都设有阻止Cookie的功能。但如果您这么做，则需要在每一次访问我们的网站时更改用户设置。如需详细了解如何更改浏览器设置，请访问您使用的浏览器的相关设置页面。</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt;"><span style="font-family: 宋体; color: #222222; font-size: 13.5pt;">&nbsp;</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><strong><span style="font-family: 宋体; font-size: 12pt;"><span style="font-family: 宋体;">三、我们如何共享、转让和公开披露您的个人</span><span style="font-family: 宋体;">/企业信息</span></span></strong></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">（一）共享</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;"><span style="font-family: 宋体;">我们不会与建业科技产品服务提供者以外的公司、组织和个人共享您的个人信息，但以下情况除外</span><span style="font-family: 宋体;">:</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">1、在获取明确同意的情况下共享:获得您的明确同意后，我们会与其他方共享您的个人/企业信息。</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">2、在法定情形下的共享:我们可能会根据法律法规规定，或按行政、司法机关依法提出的强制性要求，对外共享您的个人/企业信息。</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">（二）转让</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;"><span style="font-family: 宋体;">我们不会将您的个人</span><span style="font-family: 宋体;">/企业信息转让给任何公司、组织和个人，但以下情况除外:</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">1、在获取明确同意的情况下转让:获得您的明确同意后，我们会向其他方转让您的个人/企业信息;</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">2、在建业科技服务提供者发生合并、收购或破产清算情形，或其他涉及合并、收购或破产清算情形时，如涉及到个人信息转让，我们会要求新的持有您个人信息的公司、组织继续受本政策的约束，否则我们将要求该公司、组织和个人重新向您征求授权同意。</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">（三）公开披露</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;"><span style="font-family: 宋体;">我们仅会在以下情况下，公开披露您的个人</span><span style="font-family: 宋体;">/企业信息:</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">1、获得您明确同意或基于您的主动选择，我们可能会公开披露您的个人/企业信息;</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">2、在法律、法律程序、诉讼或政府主管部门强制性要求的情况下，我们可能会公开披露您的个人/企业信息。执法机关提出披露要求，我们会及时通知您，除非执法机关另有禁止披露的要求。</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;"><span style="font-family: 宋体;">（四）共享、转让、公开披露个人</span><span style="font-family: 宋体;">/企业信息时事先征得授权同意的例外</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;"><span style="font-family: 宋体;">以下情形中，共享、转让、公开披露您的个人</span><span style="font-family: 宋体;">/企业信息无需事先征得您的授权同意:</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">1、与国家安全、国防安全有关的;</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">2、与公共安全、公共卫生、重大公共利益有关的;</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">3、与犯罪侦查、起诉、审判和判决执行有关的;</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">4、您自行向社会公众公开的个人/企业信息;</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">5、从合法公开披露的信息中收集个人/企业信息的，如合法的新闻报道、政府信息公开渠道。根据法律规定，共享、转让经去标识化处理的个人信息，且确保数据接收方无法复原并重新识别个人信息主体的，不属于个人信息的对外共享、转让及公开披露行为，对此类数据的保存及处理将无需另行向您通知并征得您的同意。</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt;"><span style="font-family: 宋体; color: #222222; font-size: 13.5pt;">&nbsp;</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><strong><span style="font-family: 宋体; font-size: 12pt;"><span style="font-family: 宋体;">四、我们如何保护您的个人</span><span style="font-family: 宋体;">/企业信息</span></span></strong></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;"><span style="font-family: 宋体;">（一）我们已采取符合业界标准的安全防护措施保护您提供的个人</span><span style="font-family: 宋体;">/企业信息安全，防止个人/企业信息遭到未经授权访问、公开披露、使用、修改、损坏或丢失;我们同时对建业科技网站提供HTTPS(HyperTextTransferProtocoloverSecureSocketLayer)协议安全浏览方式;我们会使用加密技术提高个人/企业信息的安全性;我们会使用受信赖的保护机制防止个人/企业信息遭到恶意攻击;我们会部署访问控制机制，确保只有授权人员才可访问个人/企业信息;我们会举办安全和隐私保护培训课程，加强员工对于保护个人/企业信息重要性的认识。</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;"><span style="font-family: 宋体;">（二）我们会采取合理可行的措施，避免收集无关的个人</span><span style="font-family: 宋体;">/企业信息。我们只会在达成本政策所述目的所需的期限内保留您的个人/企业信息，除非需要延长保留期或受到法律的允许。</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;"><span style="font-family: 宋体;">（三）互联网并非绝对安全的环境，我们强烈建议您不要使用非建业科技推荐的通信方式发送个人</span><span style="font-family: 宋体;">/企业信息。请您妥善保护自己的个人/企业信息，仅在必要的情形下向他人提供。如您发现自己的个人/企业信息尤其是您的账户或密码发生泄露，请您立即联络建业科技客服，以便我们根据您的申请采取相应措施。 请使用复杂密码，协助我们保证您的账号安全。我们将尽力保障您发送给我们的任何信息的安全性。</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;"><span style="font-family: 宋体;">（四）在不幸发生个人</span><span style="font-family: 宋体;">/企业信息安全事件后，我们将按照法律法规的要求及时向您告知：安全事件的基本情况和可能的影响、我们已采取或将要采取的处置措施、您可自主防范和降低风险的建议、对您的补救措施。事件相关情况我们将以邮件、信函、电话或推送通知的方式告知您，难以逐一告知个人/企业信息主体时，我们会采取合理、有效的方式发布公告。同时，我们还将按照监管部门要求，上报个人/企业信息安全事件的处置情况。</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;"><span style="font-family: 宋体;">（五）您通过建业科技系统提交个人</span><span style="font-family: 宋体;">/企业信息，代表您同意并授权给建业科技收集、使用、共享和保护您的个人/企业信息，若您因特殊原因申请撤回授权，请及时联系我们，以便于我们做相应处理。</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt;"><span style="font-family: 宋体; color: #222222; font-size: 13.5pt;">&nbsp;</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><strong><span style="font-family: 宋体; font-size: 12pt;">五、您的权利</span></strong></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;"><span style="font-family: 宋体;">您可以通过以下方式访问及管理您的个人信息</span><span style="font-family: 宋体;">:</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">（一）访问您的个人信息</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;"><span style="font-family: 宋体;">您有权访问您的个人信息，法律法规规定的例外情况除外。您可以通过以下方式自行访问您的个人信息</span><span style="font-family: 宋体;">: 账户信息&mdash;&mdash;如果您希望访问或编辑您的账户中的个人基本信息和更改您的密码、添加安全信息，您可以通过登录账号通过&ldquo;个人中心&rdquo;执行此类操作。 如果您无法通过上述路径访问该个人信息，您可以随时通过建业科技客服与我们取得联系。我们将在30天内回复您的访问请求。</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">（二）更正或补充您的个人信息</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">当您发现我们处理的关于您的个人信息有错误时，您有权要求我们做出更正或补充。</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">（三）删除您的个人信息</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;"><span style="font-family: 宋体;">在以下情形中，您可以向我们提出删除个人信息的请求</span><span style="font-family: 宋体;">:</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">1、如果我们处理个人信息的行为违反法律法规;</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">2、如果我们收集、使用您的个人信息，却未征得您的明确同意;</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">3、如果我们处理个人信息的行为违反了与您的约定;</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">4、如果您不再使用我们的产品或服务，或您主动申请注销了账号;</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">5、如果我们不再为您提供产品或服务。</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">当您从我们的服务中删除信息后，我们可能不会立即从备份系统中删除相应的信息，但会在备份更新时删除这些信息。</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">（四）注销账户</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">在需要终止使用建业科技产品或服务时，您可以申请注销您的建业科技账户，您可以通过人工的方式申请注销建业科技账户。</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">（五）约束信息系统自动决策</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">在某些业务功能中，我们可能仅依据信息系统、算法在内的非人工自动决策机制做出决定。如果这些决定显著影响您的合法权益，您有权要求我们做出解释，我们也将在不侵害建业科技商业秘密或其他用户权益、社会公共利益的前提下提供申诉方法。</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">（六）响应您的上述请求</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">为保障安全，您可能需要提供书面请求，或以其他方式证明您的身份。我们可能会先要求您验证自己的身份，然后再处理您的请求。</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;"><span style="font-family: 宋体;">在以下情形中，按照法律法规要求，我们将无法响应您的请求</span><span style="font-family: 宋体;">:</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">1、与国家安全、国防安全有关的;</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">2、与公共安全、公共卫生、重大公共利益有关的;</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">3、与犯罪侦查、起诉、审判和执行判决有关的;</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">4、有充分证据表明您存在主观恶意或滥用权利的;</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">5、响应您的请求将导致您或其他个人、组织的合法权益受到严重损害的;</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">6、涉及商业秘密的。</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">7、需要听从法庭传票、法律命令或遵循法律程序</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">8、您没有支付与本服务相关的费用</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">9、突发自然灾害导致的问题</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">10、战争、军事行动、暴乱或武装叛乱等</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt;"><span style="font-family: 宋体; color: #222222; font-size: 13.5pt;">&nbsp;</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><strong><span style="font-family: 宋体; font-size: 12pt;">六、我们如何处理儿童的个人信息</span></strong></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;"><span style="font-family: 宋体;">我们的产品、网站和服务主要面向成人。如果没有父母或监护人的同意，儿童（不满</span><span style="font-family: 宋体;">16周岁）不得创建自己的用户账户。 对于经父母同意而收集儿童个人信息的情况，我们只会在受到法律允许、父母或监护人明确同意或者保护儿童所必要的情况下使用或公开披露此信息。 如果我们发现自己在未事先获得可证实的父母同意的情况下收集了儿童的个人信息，则会设法尽快删除相关数据。</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt;"><span style="font-family: 宋体; color: #222222; font-size: 13.5pt;">&nbsp;</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><strong><span style="font-family: 宋体; font-size: 12pt;">七、本政策如何更新</span></strong></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;"><span style="font-family: 宋体;">我们的隐私政策可能变更。</span> <span style="font-family: 宋体;">未经您明确同意，我们不会限制您按照本隐私政策所应享有的权利。</span> <span style="font-family: 宋体;">对于重大变更，我们还会提供更为显著的通知</span><span style="font-family: 宋体;">(包括我们会通过建业科技网站公示的方式进行通知)。</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;"><span style="font-family: 宋体;">本政策所指的重大变更包括但不限于</span><span style="font-family: 宋体;">:</span></span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">1、我们的服务模式发生重大变化。如处理个人信息的目的、处理的个人信息类型、个人信息的使用方式;</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">2、我们在控制权方面发生重大变化。如并购重组引起的所有者变更;</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">3、个人/企业信息共享、转让或公开披露的主要对象发生变化;</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">4、您参与个人/企业信息处理方面的权利及其行使方式发生重大变化;</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">5、我们负责处理个人/企业信息安全的责任部门、联络方式及投诉渠道发生变化时;</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">6、个人/企业信息安全影响评估报告表明存在高风险时。</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">若您在本政策修订后继续使用建业科技服务，这表示您已充分阅读、理解并接受修订后的本政策并愿意受修订后的本政策约束。</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt;"><span style="font-family: 宋体; color: #222222; font-size: 13.5pt;">&nbsp;</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><strong><span style="font-family: 宋体; font-size: 12pt;"><span style="font-family: 宋体;">八、如何联系我们如果您对本隐私政策有任何疑问、意见或建议，通过以下方式与我们联系</span><span style="font-family: 宋体;">:</span></span></strong></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;"><span style="font-family: 宋体;">电话</span><span style="font-family: 宋体;">: </span></span><span style="font-family: 宋体; color: #222222; font-size: 12pt;">400-021-3600</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">一般情况下，我们将在三十天内回复。</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;">&copy;上海建业信息科技股份有限公司 保留一切权利。</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt;"><span style="font-family: 宋体; color: #222222; font-size: 13.5pt;">&nbsp;</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; line-height: 21pt;"><span style="font-family: 宋体; color: #222222; font-size: 12pt;"><span style="font-family: 宋体;">最近更新日期</span><span style="font-family: 宋体;">:【20</span></span><span style="font-family: 宋体; color: #222222; font-size: 12pt;">22</span><span style="font-family: 宋体; color: #222222; font-size: 12pt;">】年【</span><span style="font-family: 宋体; color: #222222; font-size: 12pt;">XX</span><span style="font-family: 宋体; color: #222222; font-size: 12pt;">】月【</span><span style="font-family: 宋体; color: #222222; font-size: 12pt;">XX</span><span style="font-family: 宋体; color: #222222; font-size: 12pt;">】日</span></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; text-indent: 24pt; line-height: 21pt;"><strong><span style="font-family: 宋体; font-size: 12pt;">&nbsp;</span></strong></p>
<p class="MsoNormal" style="margin: 0pt 0pt 0.0001pt; font-family: 等线; font-size: 10.5pt; text-indent: 24pt; line-height: 21pt;"><span style="color: #ff0000;"><strong><span style="font-family: 宋体; font-size: 12pt;">我已清楚知晓并认可本协议的内容，特别是本协议中排除我方主要权利、加重我方责任及减轻或免除贵司责任的条款。我方确认对本协议的条款均无异议。</span></strong></span></p>`

export default yinsi
